apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: princeonuoha/expensy-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8706
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: expensy-config
                  key: PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: expensy-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: expensy-config
                  key: REDIS_PORT
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: expensy-secrets
                  key: DATABASE_URI
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expensy-secrets
                  key: REDIS_PASSWORD