apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: student-prince
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: prince200243@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - http01:
          ingress:
            class: nginx