apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
type: Opaque
stringData:
  DATABASE_URI: "mongodb://root:example@mongo:27017/?authSource=admin"
  REDIS_PASSWORD: "someredispassword"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"